env:
  - GO111MODULE=on

before:
  hooks:
    - go mod tidy

metadata:
  mod_timestamp: "{{ .CommitTimestamp }}"

builds:
  - binary: tengo
    env:
      - CGO_ENABLED=0
    main: ./cmd/tengo/main.go
    goos:
      - darwin
      - linux
      - windows

    goarch:
      - amd64
      - arm64

    ldflags:
      - -s -w

archives:
  - id: bee
    format_overrides:
      - goos: windows
        format: zip

    files:
      - src: build/modules
        dst: modules

checksum:
  name_template: 'checksums.txt'
changelog:
  sort: desc

nfpms:
  - id: bee
    formats:
      - deb
      - rpm

    bindir: /usr/local/sbin
