env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
  - binary: tengo
    env:
      - CGO_ENABLED=0
    main: ./cmd/tengo/main.go
    goos:
      - darwin
      - linux
      - windows
archives:
  - id: bee
    format_overrides:
      - goos: windows
        format: zip

    files:
      - none*

checksum:
  name_template: 'checksums.txt'
changelog:
  sort: desc

nfpms:
  -
    formats:
      - deb
      - rpm
